nParallelJobsPerVar: 10
doIsoGamma: true
doJets: true
doPi0: false

GJ18D: 
  # path: /home/nico/alice/GammaJet/calorimetrees/MC_Trees.txt
  isMC: true
  label: '#gamma-Jet 18 DCal'
  trainconfigs:
    100_Charged: Standard # disabled | standard | full
    101_Charged: disabled
    102_Charged: disabled
    100_Full: Standard # disabled | standard | full
    101_Full: disabled
    102_Full: disabled

LHC18_pass2: 
  path: /home/nico/alice/GammaJet/calorimetrees/Data_Trees.txt
  isMC: false
  label: 'LHC18[b-p]'
  trainconfigs:
    100_Charged: Standard # disabled | standard | full
    101_Charged: disabled
    102_Charged: disabled
    100_Full: Standard # disabled | standard | full
    101_Full: disabled
    102_Full: disabled

JJ18D:
  trainconfigs: 
    100C: disabled
    101C: disabled
    102C: disabled